# Generated by Django 5.1.7 on 2025-03-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration_image', models.ImageField(blank=True, null=True, upload_to='Methane/', verbose_name='甲烷浓度热力图')),
                ('emission_rate', models.FloatField(blank=True, null=True, verbose_name='甲烷排放率')),
                ('max_concentration', models.FloatField(blank=True, null=True, verbose_name='甲烷最高浓度值')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('sza', models.FloatField(blank=True, null=True, verbose_name='太阳天顶角(SZA)')),
                ('vza', models.FloatField(blank=True, null=True, verbose_name='视天顶角(VZA)')),
                ('u10', models.FloatField(blank=True, null=True, verbose_name='10米高度的风速(U10)')),
                ('methane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.methane', verbose_name='甲烷')),
            ],
        ),
    ]
