# Generated by Django 5.1.7 on 2025-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methaneuploadimg',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
