# Generated by Django 5.1.7 on 2025-05-07 12:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_methaneuploadimg_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methaneuploadimg',
            name='upload_image',
            field=models.ImageField(max_length=255, upload_to='MethaneUploadImg/'),
        ),
    ]
