# Generated by Django 5.1.7 on 2025-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_methaneuploadimg_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methaneuploadimg',
            name='upload_image',
            field=models.FileField(max_length=255, upload_to='MethaneUploadImg/'),
        ),
    ]
