# Generated by Django 5.1.7 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_methaneuploadimg_upload_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methaneuploadimg',
            options={'verbose_name': '上传甲烷文件', 'verbose_name_plural': '上传甲烷文件'},
        ),
    ]
