# Generated by Django 5.1.7 on 2025-05-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_methaneuploadimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '区域甲烷信息查看', 'verbose_name_plural': '区域甲烷信息查看'},
        ),
        migrations.AlterModelOptions(
            name='methane',
            options={'verbose_name': '甲烷热力图', 'verbose_name_plural': '甲烷热力图'},
        ),
    ]
