# Generated by Django 5.1.7 on 2025-05-07 22:55

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_area_options_alter_methane_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methaneuploadimg',
            name='upload_image',
            field=models.ImageField(max_length=255, upload_to='methane/MethaneUploadImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif']), main.models.validate_filename_length], verbose_name='上传图像'),
        ),
    ]
