# Generated by Django 5.1.7 on 2025-05-07 22:57

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_methaneuploadimg_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methaneuploadimg',
            name='upload_image',
            field=models.ImageField(max_length=255, upload_to='methane/MethaneUploadImg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'tif'], message='格式错误！ 请输入[13,75,75]尺寸的哨兵2号遥感图像'), main.models.validate_filename_length], verbose_name='上传图像'),
        ),
    ]
